annotations:
  artifacthub.io/links: |
    - name: Instana website
      url: https://www.instana.com
    - name: Instana Helm charts
      url: https://github.com/instana/helm-charts
apiVersion: v2
appVersion: 1.264.0
description: Instana Agent for Kubernetes
home: https://www.instana.com/
icon: https://agents.instana.io/helm/stan-logo-2020.png
maintainers:
- email: felix.marx@ibm.com
  name: FelixMarxIBM
- email: henning.treu@ibm.com
  name: htreu
- email: torsten.kohn@ibm.com
  name: tkohn
name: instana-agent
sources:
- https://github.com/instana/instana-agent-docker
version: 1.2.68
